Login:
    controller: Login
    action: showLogin

Logout:
    controller: Login
    action: logoutUser

VerifyLogin:
    controller: Login
    action: verifyLogin

Register:
    controller: Register
    action: showRegister

VerifyRegistration:
    controller: Register
    action: verifyRegistration

SuccessfulRegistration:
    controller: Login
    action: successfulRegistration

MainPage:
    controller: MainPage
    action: showMainPage