Login:
    controller: Login
    action: showLogin

VerifyLogin:
    controller: Login
    action: verifyLogin

Register:
    controller: Register
    action: showRegister

VerifyRegistration:
    controller: Register
    action: verifyRegistration